name: Start WorkFlow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  NODE_ENV: production
  API_URL: https://api.example.com
  DB_CONNECTION: mongodb://localhost:27017/mydb

jobs:
 
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Echo message
        run: echo "Hello, World from first action! environment is $NODE_ENV"
        
  build-api:
    runs-on: windows-latest  
    steps:
      
        
      - name: Echo message
        run: echo "Hello, World from the second job! and environment variables is ${{ env.NODE_ENV }}, ${{ env.API_URL }}, ${{ env.DB_CONNECTION }}"

  build-db:
    runs-on: macos-latest
    needs: build-app
    steps:
    
        
      - name: Echo message
        run: echo "Hello, World from the third job!"