name: Start WorkFlow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
 build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        -name: echo message
        run: echo "Hello, World  fist action!"
        
        build-api:
          runs-on: windows-latest  
          steps:
             

            - name: Echo message
              run: echo "Hello, World from the second job!"

              build-db:
                runs-on: macos-latest
                needs: build-app
                steps:
              

                  - name: Echo message
                    run: echo "Hello, World from the third job!"