name: Environment WorkFlow

on:
 
  workflow_dispatch:

env:
  NODE_ENV: production
  API_URL: https://api.example.com
  DB_CONNECTION: mongodb://localhost:27017/mydb

jobs:
 
  build-app:
    runs-on: ubuntu-latest
    steps:
     
      
      - name: setting up environment variables
        run: echo "COX_ENV=production" >> $GITHUB_ENV

      - name: Echo message
        run: echo "Hello, World from first action is $NODE_ENV  and $COX_ENV is COX environment" 
        
  