name: Environment WorkFlow

on:
 
  workflow_dispatch:

env:
  ID: production
  NODE_ENV: production
  API_URL: https://api.example.com
  DB_CONNECTION: mongodb://localhost:27017/mydb

jobs:
 
  build-app:
    runs-on: ubuntu-latest

    environment: 
        name: production
        url : " https://production.example.com"
        
    steps:
     
      
      - name: setting up environment variables
        run: echo "COX_ENV=production" >> $GITHUB_ENV

      - name: Echo message
        run: echo "Hello, World from first action is COX_ENV is COX environment" 

      - name: Print secrets
        run: echo "The secret APPKey is ${{ secrets.PROD_APP_KEY }}"
        
  