name: Start WorkFlow

on:
  
  workflow_dispatch:

env:
  NODE_ENV: production
  API_URL: https://api.example.com
  DB_CONNECTION: mongodb://localhost:27017/mydb

jobs:
 
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Echo message
        run: echo "Hello, World from first action!"
        
  build-api:
    runs-on: windows-latest  
    steps:
      
        
      - name: Echo message
        run: echo "Hello, World from the second job! and environment variables is ${{ env.NODE_ENV }}, ${{ env.API_URL }}, ${{ secrets.API_KEY }}"

  build-db:
    runs-on: macos-latest
    needs: build-app
    steps:
    
        
      - name: Echo message
        run: echo "Hello, World from the third job! environment Secret is  $secrets.API_KEY"