name: Secret WorkFlow

on:
  
  workflow_dispatch:

env:
  NODE_ENV: production
  API_URL: https://api.example.com
  

jobs:
 
  build-app:
    runs-on: ubuntu-latest
    steps:
- name: Send Notification to Slack channel
  run: |
    curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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

